/**
 * 
 */
package net.azib.ipscan.gui.actions;

import java.io.File;
import java.io.FileWriter;

import net.azib.ipscan.gui.UserErrorException;

/**
 * The cross-platform terminal launcher
 * 
 * @author anton
 */
public class TerminalLauncher {
	
	/**
	 * Launches the execString in the terminal.
	 * Supports Linux/Unix, MacOS, and Windows
	 * @param execString the command to launch
	 * @param workingDir the working directory (or null)
	 */
	public static void launchInTerminal(String execString, File workingDir) {
		String osName = System.getProperty("os.name");

		try {
			if (osName.startsWith("Windows")) {
				// generate a bat file :-)
				File batFile = File.createTempFile("launch", ".bat");
				batFile.deleteOnExit();
				FileWriter writer = new FileWriter(batFile);
				writer.write("@rem This is a temporary file generated by Angry IP Scanner\n\n" +
						     execString + "\npause > nul\n");
				writer.close();
				
				// TODO: test this on Windows!!!
				Runtime.getRuntime().exec(batFile.getAbsolutePath(), null, workingDir);
			}
			else { // assume Linux or other Unix
				// TODO: test this on MacOS!!!
				// TODO: maybe gnome-terminal, konsole, and MacOS-specific terminal should be tried as well...
				Runtime.getRuntime().exec(new String[] {"xterm", "-e", "bash", "-c", execString + ";bash"}, null, workingDir);
			}
		}
		catch (Exception e) {
			throw new UserErrorException("openTerminal.failed", execString);
		}
	}
}
