#!/bin/sh
BASEDIR=`dirname "$0"`
# MacOS will prompt to download Oracle JDK if it's not installed
exec java --add-opens java.base/java.net=ALL-UNNAMED -XstartOnFirstThread -jar "$BASEDIR"/ipscan*.jar
